# Generated by Django 5.0.4 on 2024-05-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NegativeKey',
        ),
        migrations.DeleteModel(
            name='PositiveKey',
        ),
    ]
